apiVersion: v1
kind: ConfigMap
metadata:
  name: edgecom-app-config
data:
  config.yaml: |
    server:
      port: 8080
      url: "https://api.edgecomenergy.net/core/asset/3662953a-1396-4996-a1b6-99a0c5e7a5de/series"
    database:
      host: "edgecom-db-service"
      port: 5432
      user: "edgecom"
      password: "edgecom"
      name: "edgecom"
      ssl_mode: "disable"
      max_connections: 10
      connection_timeout: 30