apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgecom
  labels:
    app: edgecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgecom
  template:
    metadata:
      labels:
        app: edgecom
    spec:
      containers:
      - name: edgecom
        image: edgecom:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "edgecom-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: edgecom-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: edgecom-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: edgecom-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: edgecom-app-config
          items:
          - key: config.yaml
            path: config.yaml