apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgecom
  labels:
    app: edgecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgecom
  template:
    metadata:
      labels:
        app: edgecom
    spec:
      containers:
      - name: edgecom
        image: edgecom:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: edgecom-app-config
          items:
          - key: config.yaml
            path: config.yaml