// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/timeseries.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeSeriesService_QueryTimeSeries_FullMethodName = "/edgecom.TimeSeriesService/QueryTimeSeries"
)

// TimeSeriesServiceClient is the client API for TimeSeriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeSeriesServiceClient interface {
	QueryTimeSeries(ctx context.Context, in *TimeSeriesRequest, opts ...grpc.CallOption) (*TimeSeriesResponse, error)
}

type timeSeriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeSeriesServiceClient(cc grpc.ClientConnInterface) TimeSeriesServiceClient {
	return &timeSeriesServiceClient{cc}
}

func (c *timeSeriesServiceClient) QueryTimeSeries(ctx context.Context, in *TimeSeriesRequest, opts ...grpc.CallOption) (*TimeSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeSeriesResponse)
	err := c.cc.Invoke(ctx, TimeSeriesService_QueryTimeSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeSeriesServiceServer is the server API for TimeSeriesService service.
// All implementations must embed UnimplementedTimeSeriesServiceServer
// for forward compatibility.
type TimeSeriesServiceServer interface {
	QueryTimeSeries(context.Context, *TimeSeriesRequest) (*TimeSeriesResponse, error)
	mustEmbedUnimplementedTimeSeriesServiceServer()
}

// UnimplementedTimeSeriesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeSeriesServiceServer struct{}

func (UnimplementedTimeSeriesServiceServer) QueryTimeSeries(context.Context, *TimeSeriesRequest) (*TimeSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTimeSeries not implemented")
}
func (UnimplementedTimeSeriesServiceServer) mustEmbedUnimplementedTimeSeriesServiceServer() {}
func (UnimplementedTimeSeriesServiceServer) testEmbeddedByValue()                           {}

// UnsafeTimeSeriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeSeriesServiceServer will
// result in compilation errors.
type UnsafeTimeSeriesServiceServer interface {
	mustEmbedUnimplementedTimeSeriesServiceServer()
}

func RegisterTimeSeriesServiceServer(s grpc.ServiceRegistrar, srv TimeSeriesServiceServer) {
	// If the following call pancis, it indicates UnimplementedTimeSeriesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeSeriesService_ServiceDesc, srv)
}

func _TimeSeriesService_QueryTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeSeriesServiceServer).QueryTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeSeriesService_QueryTimeSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeSeriesServiceServer).QueryTimeSeries(ctx, req.(*TimeSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeSeriesService_ServiceDesc is the grpc.ServiceDesc for TimeSeriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeSeriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edgecom.TimeSeriesService",
	HandlerType: (*TimeSeriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTimeSeries",
			Handler:    _TimeSeriesService_QueryTimeSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/timeseries.proto",
}
